"""fix sync state2

Revision ID: fae1d041ded7
Revises: d9a452a4a422
Create Date: 2026-04-22 11:53:01.750283

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fae1d041ded7"
down_revision: Union[str, Sequence[str], None] = "d9a452a4a422"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sync_state",
        sa.Column("last_changed_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.drop_column("sync_state", "last_chenged_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sync_state",
        sa.Column(
            "last_chenged_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("sync_state", "last_changed_at")
    # ### end Alembic commands ###
